spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graphql_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


  graphql:
    graphiql:
      enabled: true   # UI for testing
